#!/bin/bash
# Deploy the latest client build to the dev patch server.
# Downloads the meridian_client CI artifact (which includes patchinfo.txt and club.exe)
# and rsyncs it to /opt/m59-patch/ on dev.emfiftynine.info.
set -euo pipefail

REPO="roge-life/Meridian59_900_1.0"
WEB_HOST="dev.emfiftynine.info"
STAGING=$(mktemp -d)
trap 'rm -rf "$STAGING"' EXIT

echo "==> Fetching latest meridian_client artifact run ID"
CLIENT_RUN=$(gh run list --repo "$REPO" --workflow "buildonpush.yml" --status success --limit 1 --json databaseId -q '.[0].databaseId')
echo "    Run: $CLIENT_RUN"

echo "==> Downloading meridian_client artifact"
gh run download "$CLIENT_RUN" --repo "$REPO" --name meridian_client --dir "$STAGING/client"

echo "    Files in artifact:"
ls "$STAGING/client/" | head -10

# Sanity check — patchinfo.txt must be present (generated by CI)
if [ ! -f "$STAGING/client/patchinfo.txt" ]; then
    echo "ERROR: patchinfo.txt missing from artifact — was the CI patch manifest step run?" >&2
    exit 1
fi

echo "==> Syncing to $WEB_HOST:/opt/m59-patch/"
ssh -o StrictHostKeyChecking=no "root@$WEB_HOST" "mkdir -p /opt/m59-patch"
rsync -rlpt --delete \
    "$STAGING/client/" "root@$WEB_HOST:/opt/m59-patch/"

echo "==> Verifying patch manifest on server"
ssh -o StrictHostKeyChecking=no "root@$WEB_HOST" \
    'wc -l /opt/m59-patch/patchinfo.txt; head -c 200 /opt/m59-patch/patchinfo.txt'

echo "==> Patch deploy complete"
echo "    Patch files served at https://$WEB_HOST/patch/"
